title: SH4NNU
subtitle: Computer Science Undergrad | OSS | Operating Systems | Compilers | Foodie
description: >- # this means to ignore newlines until "baseurl:"
  This is a place where I express my views and share knowledge with you.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Contact Me
      url : /contact



# Edit these details

author_logo: profile.png
author: Manikishan Ghantasala
author_bio: Hello. I'm Manikishan, a CS undergrad from Amrita Vishwa Vidyapeetham , Kollam, Kerala. I am a passionate developer and an artist, in a tireless endeavor to seek knowledge. I love to build and examine the internals of softwares, draw portraits, and watch anime. This blog is a place where I scribble my thoughts and share my knowledge and experience with the world of wonderful readers like you. 
author_email: "manikishanghantasala@gmail.com"
author_location: India
author_website_url: "http://sh4nnu.codes"
typewrite-text: An OSS developer. Love to know how things really work ;)

author_work_experiences:
            - company_name: NetBSD
              company_logo: NETBSD-logo.png
              company_url: https://summerofcode.withgoogle.com/archive/2019/organizations/6058884492427264/
              designation: Google Summer of Code’19 - Developer Intern
              description: Added a KNF (NetBSD style) configuration for clang-format and added support to format according to NetBSD Kernel coding styles.
              visibility: true

author_certification_details:
              - certificate_logo: cert.jpg
                certificate_name: Build a Modern Computer from First Principles - From Nand to Tetris (Project-Centered Course)
                certificate_url: https://www.coursera.org/account/accomplishments/certificate/HQT2CTMC4D5F
                certificate_degree: Nand2Tetris
                description: Hebrew University of Jerusalem   -- Sept 2018
                visibility: true

              - certificate_logo: cert.jpg
                certificate_name: A specialisation of three courses on courrent, parallel and distributed programming.
                certificate_url: https://www.coursera.org/account/accomplishments/specialization/certificate/DQUT2AGRUL4K
                certificate_degree: Parallel-Concurrent-Dirstributed programming specialisation
                description: Rice University   -- Apr 2020
                visibility: true

              - certificate_logo: cert.jpg
                certificate_name: A introduction course to Front-End Web development, with HTML, CSS and JQuery.
                certificate_url: https://classroom.udacity.com/courses/ud304-in
                certificate_degree: Google India Challenge Scholarship - Front-End Web Dev
                description: Udacity   -- 2017
                visibility: true
              
author_project_details:
              - project_thumbnail: NAND_ANSI.svg
                project_title: Nand2Tetris
                project_description: Built a basic 16-bit CPU with a language similar to VHDL, and built a compiler, OS that run on the virtual CPU over which you can play a Tetris game written in a custom made programming language.
                project_url: http://github.com/sh4nnu/nand2tetris
                visibility: true
              - project_thumbnail: pixel-art.png
                project_title: Pixel Art Maker
                project_description: A 8-bit graphic creation tool made by JQuery, HTML and CSS.
                # project_url: https://hack4r.com
                visibility: true

# social links
twitter_username: ManikishanG
github_username:  sh4nnu
linkedin_username: manikishan-ghantasala-76375a151
instagram_username: manikishanghantasala
telegram_username: manikishan

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

disqus_shortname: sh4nnu-1
#hyvor_talk_website_id: 753

# wakatime username (coding activity)
wakatime_username: sh4nnu

# mailchimp embedded form url (newsletter):
#
# formspree (contact form)
formspree_email: manikishanghantasala@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_certification_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
# collections:
#  - products

# # Gallery
# defaults:
#   -
#     scope:
#       path: "gallery"
#     values:
#       permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
